env: prod

fluent-bit:
  enabled: true
  backend:
    type: splunk
    splunk:
      host:
      port: 8088
  env:
    - name: K8S_CLUSTER
      value: prod

kibana:
  enabled: true
  elasticsearchHosts: ''
  replicas: 1
  protocol: http
  ingress:
    enabled: true
    hosts:
      - kibana.k8s.example.com
    tls:
      - hosts:
          - kibana.k8s.example.com
  fullnameOverride: kibana

prometheus-operator:

  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.k8s.example.com

  kubeControllerManager:
    endpoints:
      -
      -

  kubeEtcd:
    endpoints:
      -
      -
    serviceMonitor:
      scheme: https
      caFile: "/etc/prometheus/secrets/prometheus-etcd/etcd-ca"
      certFile: "/etc/prometheus/secrets/prometheus-etcd/etcd-client"
      keyFile: "/etc/prometheus/secrets/prometheus-etcd/etcd-client-key"

  prometheus:
    ingress:
      enabled: true
      hosts:
        - prometheus.k8s.example.com
    prometheusSpec:
      secrets:
        - prometheus-etcd
      retentionSize: 2GB

externalServicesEndpoints:
  elasticsearch:
    - ip:
    - ip:
  postgresGc:
    - ip:
    - ip:
  postgresProfile:
    - ip:
    - ip:
  redis:
    - ip:
    - ip:
  kafka:
    - ip:
    - ip:

externalServicesMetricsPorts:
  elasticsearch: 9273
  postgresGc: 9273
  postgresProfile: 9273
  redis: 9273
  kafka: 9273