apiVersion: v1
kind: Secret
metadata:
  name: prometheus-etcd
type: Opaque
data:
  etcd-ca: {{ .Values.etcd.tls.ca }}
  etcd-client: {{ .Values.etcd.tls.client }}
  etcd-client-key: {{ .Values.etcd.tls.clientKey }}