dependencies:
  - name: prometheus-operator
    version: 6.7.4
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: prometheus-operator.enabled

  - name: grafana-dashboards-1.10
    version: 0.1.0
    repository: file://subcharts/grafana-dashboards-1.10
    condition: grafana-dashboards-1-10.enabled

  - name: kibana
    version: 7.4.1
    repository: https://helm.elastic.co
    condition: kibana.enabled

  - name: fluent-bit
    version: 2.8.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: fluent-bit.enabled

  - name: metrics-server
    version: 2.8.8
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: metrics-server.enabled